"""Canonical feature column list for v1 baseline v152 reproduction.

IMPORTANT: Column ORDER matters. LightGBM's colsample_bytree < 1.0 samples
columns by position using the seeded RNG. If you reorder the list, the same
seeded sampling picks different columns for each tree, producing a different
model even with identical features, data, and seeds.

This list is in the EXACT ORDER auto-discovery would have returned on
2026-04-05 (BASELINE measurement date, before iter-162 added entropy/CUSUM).

Reproduced from current parquet schema by excluding the 11 entropy_cusum
features (positions 13-23 in current schema). Feature groups register in
alphabetical order: calendar, interaction, mean_reversion, momentum,
statistical, trend, volatility, volume. Within each group the order is
defined by that group's feature-generation code.

Do NOT sort alphabetically. Do NOT add or remove columns without re-measuring
the baseline.
"""

from __future__ import annotations

BASELINE_FEATURE_COLUMNS_V152: tuple[str, ...] = (
    "cal_hour_norm",
    "cal_dow_norm",
    "interact_rsi_x_adx",
    "interact_stoch_x_adx",
    "interact_natr_x_adx",
    "interact_rsi_x_natr",
    "interact_ret1_x_natr",
    "interact_ret1_x_ret3",
    "mr_bb_pctb_10",
    "mr_bb_pctb_15",
    "mr_bb_pctb_20",
    "mr_bb_pctb_30",
    "mr_zscore_10",
    "mr_zscore_20",
    "mr_zscore_30",
    "mr_zscore_50",
    "mr_zscore_100",
    "mr_dist_vwap",
    "mr_rsi_extreme_7",
    "mr_rsi_extreme_14",
    "mr_rsi_extreme_21",
    "mr_pct_from_high_5",
    "mr_pct_from_high_10",
    "mr_pct_from_high_20",
    "mr_pct_from_high_50",
    "mr_pct_from_high_100",
    "mr_pct_from_low_5",
    "mr_pct_from_low_10",
    "mr_pct_from_low_20",
    "mr_pct_from_low_50",
    "mr_pct_from_low_100",
    "mr_dist_sma_10",
    "mr_dist_sma_20",
    "mr_dist_sma_50",
    "mom_rsi_5",
    "mom_rsi_7",
    "mom_rsi_9",
    "mom_rsi_14",
    "mom_rsi_21",
    "mom_rsi_30",
    "mom_macd_line_8_21_5",
    "mom_macd_hist_8_21_5",
    "mom_macd_signal_8_21_5",
    "mom_macd_line_12_26_9",
    "mom_macd_hist_12_26_9",
    "mom_macd_signal_12_26_9",
    "mom_macd_line_5_13_3",
    "mom_macd_hist_5_13_3",
    "mom_macd_signal_5_13_3",
    "mom_stoch_k_5",
    "mom_stoch_d_5",
    "mom_stoch_k_9",
    "mom_stoch_d_9",
    "mom_stoch_k_14",
    "mom_stoch_d_14",
    "mom_stoch_k_21",
    "mom_stoch_d_21",
    "mom_willr_7",
    "mom_willr_14",
    "mom_willr_21",
    "mom_roc_3",
    "mom_roc_5",
    "mom_roc_10",
    "mom_roc_15",
    "mom_roc_20",
    "mom_roc_30",
    "mom_mom_5",
    "mom_mom_10",
    "mom_mom_15",
    "mom_mom_20",
    "stat_return_1",
    "stat_return_2",
    "stat_return_3",
    "stat_return_5",
    "stat_return_10",
    "stat_return_15",
    "stat_return_20",
    "stat_return_30",
    "stat_log_return_1",
    "stat_log_return_3",
    "stat_log_return_5",
    "stat_log_return_10",
    "stat_log_return_20",
    "stat_autocorr_lag1",
    "stat_autocorr_lag5",
    "stat_autocorr_lag10",
    "stat_skew_10",
    "stat_skew_20",
    "stat_skew_30",
    "stat_skew_50",
    "stat_kurtosis_10",
    "stat_kurtosis_20",
    "stat_kurtosis_30",
    "stat_kurtosis_50",
    "trend_adx_7",
    "trend_plus_di_7",
    "trend_minus_di_7",
    "trend_adx_14",
    "trend_plus_di_14",
    "trend_minus_di_14",
    "trend_adx_21",
    "trend_plus_di_21",
    "trend_minus_di_21",
    "trend_aroon_down_14",
    "trend_aroon_up_14",
    "trend_aroon_osc_14",
    "trend_aroon_down_25",
    "trend_aroon_up_25",
    "trend_aroon_osc_25",
    "trend_aroon_down_50",
    "trend_aroon_up_50",
    "trend_aroon_osc_50",
    "trend_ema_5",
    "trend_ema_9",
    "trend_ema_12",
    "trend_ema_21",
    "trend_ema_50",
    "trend_ema_100",
    "trend_sma_10",
    "trend_sma_20",
    "trend_sma_50",
    "trend_sma_100",
    "trend_ema_cross_5_12",
    "trend_ema_cross_9_21",
    "trend_ema_cross_12_50",
    "trend_sma_cross_10_50",
    "trend_sma_cross_20_50",
    "trend_sma_cross_20_100",
    "trend_supertrend_7_3",
    "trend_supertrend_10_2",
    "trend_supertrend_14_3",
    "trend_psar_af",
    "trend_psar_dir",
    "vol_atr_5",
    "vol_atr_7",
    "vol_atr_10",
    "vol_atr_14",
    "vol_atr_21",
    "vol_natr_7",
    "vol_natr_14",
    "vol_natr_21",
    "vol_bb_bandwidth_10",
    "vol_bb_pctb_10",
    "vol_bb_bandwidth_15",
    "vol_bb_pctb_15",
    "vol_bb_bandwidth_20",
    "vol_bb_pctb_20",
    "vol_bb_bandwidth_30",
    "vol_bb_pctb_30",
    "vol_range_spike_12",
    "vol_range_spike_24",
    "vol_range_spike_36",
    "vol_range_spike_48",
    "vol_range_spike_72",
    "vol_range_spike_96",
    "vol_garman_klass_10",
    "vol_garman_klass_20",
    "vol_garman_klass_30",
    "vol_garman_klass_50",
    "vol_parkinson_10",
    "vol_parkinson_20",
    "vol_parkinson_30",
    "vol_parkinson_50",
    "vol_hist_5",
    "vol_hist_10",
    "vol_hist_20",
    "vol_hist_30",
    "vol_hist_50",
    "vol_obv",
    "vol_cmf_10",
    "vol_cmf_14",
    "vol_cmf_20",
    "vol_mfi_7",
    "vol_mfi_10",
    "vol_mfi_14",
    "vol_mfi_21",
    "vol_ad",
    "vol_vwap",
    "vol_taker_buy_ratio",
    "vol_taker_buy_ratio_sma_5",
    "vol_taker_buy_ratio_sma_10",
    "vol_taker_buy_ratio_sma_20",
    "vol_taker_buy_ratio_sma_50",
    "vol_volume_pctchg_3",
    "vol_volume_pctchg_5",
    "vol_volume_pctchg_10",
    "vol_volume_pctchg_15",
    "vol_volume_pctchg_20",
    "vol_volume_pctchg_30",
    "vol_volume_rel_5",
    "vol_volume_rel_10",
    "vol_volume_rel_20",
    "vol_volume_rel_50",
)
