"""iter-v1/085 structure pre-screen for ALGOUSDT (the /084 anti-CRV-trap gate).

USER DIRECTIVE 2026-06-09: keep mining; apply the /084 structure-gate lesson.
The CRV/084 trap: a near-zero trivial baseline that is PURE NOISE (not edge
headroom) cratered ML (IS -2.47). The refined selector
(feedback_v1_negative_trivial_baseline_selector) adds a structure test so we
do not confuse "no trivial trend" with "no learnable signal".

GATES (all IS-only, klines strictly before OOS_CUTOFF 2025-03-24):
- GATE 1: trivial-momentum baseline min-horizon (5d/21d/50d), fee-adj TS-mom.
          gate1_pass = (min <= +0.15). REUSED from analysis/iteration_v1-084/.
- GATE 2 PRIMARY: fast single-seed LightGBM probe IS Sharpe >= +0.30
          (orchestrator-level probe; this script does GATE 2 SECONDARY +
          TERTIARY — the cheap structure proxies).
- GATE 2 SECONDARY (KEY): max single-feature-vs-LABEL |IC| (Spearman, IS-only)
          >= 0.04. The label is the PRODUCTION triple-barrier directional sign
          generated by the SAME label_trades the specialists call:
            use_atr_labeling=True, atr = close * vol_natr_21 / 100,
            atr_tp_multiplier / atr_sl_multiplier (ATR-scaled barriers),
            label_timeout_minutes=10080 (= 21 bars @ 8h),
            sigma_source="natr"  (matches run_baseline_v1.py:546-562).
          ALGO has no tuned ATR mults yet, so the label uses the MODAL
          Model-A pattern (TP=2.9 / SL=1.45) as primary, with the DOT pattern
          (3.5 / 1.75) as a barrier-sensitivity check.
- GATE 2 TERTIARY: return-autocorr magnitude max(|acf_1|,|acf_3|,|acf_7|) >= 0.03.

structure_signal verdict on PRIMARY max|IC|:
  STRONG   >= 0.06
  MODERATE 0.04 - 0.06
  WEAK     0.02 - 0.04
  NOISE    < 0.02   (the CRV trap)

IS-ONLY DISCIPLINE: every number uses only bars with open_time < OOS_CUTOFF.
Asserted at runtime. Features are read from the SAME production parquet the
specialist reads. The label's forward scan stays within IS bars because the
master df is restricted to IS rows (final 21 label entries get a truncated
timeout scan exactly as the production walk-forward truncates the last training
month — no OOS leak). Those tail rows are dropped before the IC computation.
"""

from __future__ import annotations

import datetime as dt

import numpy as np
import pandas as pd
import pyarrow.parquet as pq
from scipy.stats import spearmanr

from crypto_trade.strategies.ml.labeling import label_trades

SYMBOL = "ALGOUSDT"
OOS_CUTOFF_MS = int(dt.datetime(2025, 3, 24, tzinfo=dt.timezone.utc).timestamp() * 1000)
BARS_PER_DAY = 3  # 8h cadence
ANN = np.sqrt(BARS_PER_DAY * 365.0)
FEE = 0.0005  # 0.05% per side (trivial baseline)
HORIZONS = {"5d": 15, "21d": 63, "50d": 150}  # bars

# Production specialist label config (run_baseline_v1.py:546-562 + lgbm.py:204).
LABEL_TIMEOUT_MIN = 10080  # 21 bars @ 8h
TIMEOUT_BARS = LABEL_TIMEOUT_MIN // 480  # 21
ATR_COLUMN = "vol_natr_21"
LABEL_FEE_PCT = 0.1
# ATR multiplier patterns across existing specialists.
ATR_PATTERNS = {
    "modelA_2.9_1.45": (2.9, 1.45),  # ETH/064 + BTC/065 modal pattern → PRIMARY
    "dot_3.5_1.75": (3.5, 1.75),  # DOT/063 pattern → sensitivity check
}
PRIMARY_PATTERN = "modelA_2.9_1.45"

# Cheap candidate signals to IC against the label (production column names).
# oi_delta / funding unavailable for ALGO in this universe → taker-buy proxy used.
CANDIDATE_COLS = {
    "ret_5d": "stat_return_15",      # 15 bars = 5d
    "ret_21d": "stat_return_63",     # may not exist → fallback below
    "rsi_14": "mom_rsi_14",
    "natr_30": "vol_natr_21",        # closest available NATR (no natr_30 col)
    "vol_bb_bandwidth": "vol_bb_bandwidth_20",
    "taker_buy_ratio": "vol_taker_buy_ratio",
}


def load_is_klines(sym: str) -> pd.DataFrame:
    df = pd.read_csv(f"data/{sym}/8h.csv")
    df = df[df["open_time"] < OOS_CUTOFF_MS].copy()
    df = df.sort_values("open_time").reset_index(drop=True)
    assert df["open_time"].max() < OOS_CUTOFF_MS, f"{sym} OOS leak (klines)!"
    for c in ("open", "high", "low", "close"):
        df[c] = df[c].astype(float)
    df["symbol"] = sym
    return df


def load_is_features(sym: str) -> pd.DataFrame:
    t = pq.read_table(f"data/features/{sym}_8h_features.parquet")
    fdf = t.to_pandas()
    fdf = fdf[fdf["open_time"] < OOS_CUTOFF_MS].copy()
    fdf = fdf.sort_values("open_time").reset_index(drop=True)
    assert fdf["open_time"].max() < OOS_CUTOFF_MS, f"{sym} OOS leak (features)!"
    return fdf


# ----------------------- GATE 1: trivial TS-momentum -----------------------
def trivial_mom_sharpe(close: pd.Series, n: int) -> float:
    mom = close.pct_change(n)
    pos = np.sign(mom).shift(1)
    bar_ret = close.pct_change()
    gross = pos * bar_ret
    turnover = pos.diff().abs().fillna(0.0)
    net = (gross - FEE * turnover).dropna()
    if net.std(ddof=1) == 0 or len(net) < 30:
        return float("nan")
    return float(net.mean() / net.std(ddof=1) * ANN)


def make_label(kdf: pd.DataFrame, fdf: pd.DataFrame, atr_tp: float, atr_sl: float) -> pd.Series:
    """Production triple-barrier directional sign via label_trades + NATR ATR."""
    # Align NATR onto kline open_time (production: searchsorted exact match).
    natr = fdf.set_index("open_time")[ATR_COLUMN]
    natr_aligned = kdf["open_time"].map(natr)  # NaN where no feature row
    close = kdf["close"].to_numpy()
    atr_values = close * natr_aligned.to_numpy() / 100.0  # price-unit ATR

    master = kdf[["symbol", "open_time", "close_time", "open", "high", "low", "close"]].copy()
    cand = np.arange(len(master), dtype=np.intp)
    labels, _w, _lp, _sp = label_trades(
        master=master,
        candidate_indices=cand,
        tp_pct=atr_tp,  # ATR multiplier (use_atr_labeling path)
        sl_pct=atr_sl,
        timeout_minutes=LABEL_TIMEOUT_MIN,
        fee_pct=LABEL_FEE_PCT,
        atr_values=atr_values,
        label_mode="triple_barrier",
    )
    return pd.Series(labels, index=kdf.index, dtype=float)


def main() -> None:
    kdf = load_is_klines(SYMBOL)
    fdf = load_is_features(SYMBOL)
    is_years = (kdf["open_time"].max() - kdf["open_time"].min()) / 1000 / 86400 / 365.25
    n_bars = len(kdf)
    print(f"{SYMBOL}: IS kline bars={n_bars}  IS feature rows={len(fdf)}  IS years={is_years:.2f}")
    assert is_years >= 4.0, "insufficient data — <4y"

    close = kdf["close"]

    # ---- GATE 1 ----
    s = {k: trivial_mom_sharpe(close, n) for k, n in HORIZONS.items()}
    trivial_min = float(np.nanmin(list(s.values())))
    gate1_pass = bool(trivial_min <= 0.15)
    print("\n=== GATE 1: trivial TS-momentum (fee-adj, IS-only) ===")
    for k in HORIZONS:
        print(f"  {k:>4}: {s[k]:+.3f}")
    print(f"  min_horizon: {trivial_min:+.3f}   gate1_pass(<=+0.15): {gate1_pass}")
    print("  (cross-check /084 eda_results: s5=0.242 s21=0.402 s50=0.735)")

    # ---- Resolve candidate feature columns (with fallbacks) ----
    fcols = set(fdf.columns)
    resolved: dict[str, str] = {}
    for name, col in CANDIDATE_COLS.items():
        if col in fcols:
            resolved[name] = col
        elif name == "ret_21d" and "stat_return_60" in fcols:
            resolved[name] = "stat_return_60"
        elif name == "ret_21d":
            # compute 63-bar return inline from close as a last resort
            resolved[name] = "__ret63_inline__"
        else:
            resolved[name] = col  # will produce NaN IC if absent
    feat_frame = pd.DataFrame(index=kdf.index)
    for name, col in resolved.items():
        if col == "__ret63_inline__":
            feat_frame[name] = close.pct_change(63)
        elif col in fcols:
            mapped = kdf["open_time"].map(fdf.set_index("open_time")[col])
            feat_frame[name] = mapped.to_numpy()
        else:
            feat_frame[name] = np.nan
    print(f"\n  resolved feature cols: {resolved}")

    tail_guard = TIMEOUT_BARS
    valid_idx = kdf.index[: len(kdf) - tail_guard]

    # ---- GATE 2 SECONDARY: IC for each ATR pattern ----
    results = {}
    for pat_name, (atr_tp, atr_sl) in ATR_PATTERNS.items():
        lbl_full = make_label(kdf, fdf, atr_tp, atr_sl)
        lbl = lbl_full.loc[valid_idx]
        n_long = int((lbl == 1).sum())
        n_short = int((lbl == -1).sum())
        n_lab = len(lbl)
        print(f"\n=== GATE 2 SECONDARY | label pattern {pat_name} (ATR tp={atr_tp} sl={atr_sl}, "
              f"timeout={TIMEOUT_BARS} bars) ===")
        print(f"  labeled rows={n_lab}  long={n_long} ({n_long/n_lab*100:.1f}%)  "
              f"short={n_short} ({n_short/n_lab*100:.1f}%)")
        ic_rows = []
        for name in resolved:
            f = feat_frame[name].loc[valid_idx]
            mask = f.notna() & lbl.notna()
            if mask.sum() < 100:
                ic, n_eff = float("nan"), int(mask.sum())
            else:
                rho, _ = spearmanr(f[mask], lbl[mask])
                ic, n_eff = float(rho), int(mask.sum())
            ic_rows.append((name, ic, n_eff))
            print(f"  {name:>18}: IC={ic:+.4f}  |IC|={abs(ic):.4f}  n={n_eff}")
        abs_ics = [abs(ic) for _, ic, _ in ic_rows if not np.isnan(ic)]
        max_ic = float(max(abs_ics)) if abs_ics else float("nan")
        print(f"  MAX |IC| = {max_ic:.4f}")
        results[pat_name] = dict(max_ic=max_ic, ic_rows=ic_rows,
                                 long_frac=round(n_long / n_lab, 3))

    primary_max_ic = results[PRIMARY_PATTERN]["max_ic"]

    # ---- GATE 2 TERTIARY: return autocorr ----
    bar_ret = close.pct_change().dropna()
    acf = {lag: float(bar_ret.autocorr(lag=lag)) for lag in (1, 3, 7)}
    autocorr_mag = float(max(abs(acf[1]), abs(acf[3]), abs(acf[7])))
    print("\n=== GATE 2 TERTIARY: return autocorr (IS-only) ===")
    for lag in (1, 3, 7):
        print(f"  acf_{lag}: {acf[lag]:+.4f}")
    print(f"  autocorr_mag = {autocorr_mag:.4f}")

    # ---- structure_signal verdict on PRIMARY ----
    if primary_max_ic >= 0.06:
        sig = "STRONG"
    elif primary_max_ic >= 0.04:
        sig = "MODERATE"
    elif primary_max_ic >= 0.02:
        sig = "WEAK"
    else:
        sig = "NOISE"

    print("\n=== VERDICT (PRIMARY pattern = " + PRIMARY_PATTERN + ") ===")
    print(f"  coin                 = {SYMBOL}")
    print(f"  trivial_baseline_min = {trivial_min:+.3f}")
    print(f"  max_feature_label_ic = {primary_max_ic:.4f}")
    sens = results['dot_3.5_1.75']['max_ic']
    print(f"  (sensitivity DOT pattern max|IC| = {sens:.4f})")
    print(f"  autocorr_mag         = {autocorr_mag:.4f}")
    print(f"  gate1_pass           = {gate1_pass}")
    print(f"  structure_signal     = {sig}")

    out = pd.DataFrame(
        [
            dict(
                coin=SYMBOL,
                is_years=round(is_years, 2),
                n_bars=n_bars,
                s5=round(s["5d"], 3),
                s21=round(s["21d"], 3),
                s50=round(s["50d"], 3),
                trivial_baseline_min=round(trivial_min, 3),
                gate1_pass=gate1_pass,
                max_feature_label_ic=round(primary_max_ic, 4),
                max_ic_dot_pattern=round(sens, 4),
                autocorr_mag=round(autocorr_mag, 4),
                acf_1=round(acf[1], 4),
                acf_3=round(acf[3], 4),
                acf_7=round(acf[7], 4),
                long_frac=results[PRIMARY_PATTERN]["long_frac"],
                structure_signal=sig,
            )
        ]
    )
    out.to_csv("analysis/iteration_v1-085/structure_prescreen_algo.csv", index=False)
    detail = []
    for pat, r in results.items():
        for name, ic, n_eff in r["ic_rows"]:
            detail.append(dict(pattern=pat, feature=name, ic=round(ic, 4), n=n_eff))
    pd.DataFrame(detail).to_csv("analysis/iteration_v1-085/feature_ic_algo.csv", index=False)
    print("\nwrote analysis/iteration_v1-085/structure_prescreen_algo.csv + feature_ic_algo.csv")


if __name__ == "__main__":
    main()
