"""Forward paper desk for the CUP-20 winner, team-02 ``channel-position-ls``.

This package *consumes* the frozen tournament stack in ``crypto_trade.cup20`` and never modifies
it: ``src/crypto_trade/cup20`` is hash-bound by ``tournament/cup20/activation-freeze.json``. The
desk is paper-only -- there is no signed client and no order path anywhere in it.
"""

from crypto_trade.cup20_desk.authority import (
    AUTHORITY_FIELDS,
    SCHEMA_VERSION,
    TOURNAMENT,
    WINNER_CANDIDATE_ID,
    WINNER_TEAM_ID,
    DeploymentChangedError,
    DeskAuthority,
    candidate_root,
    current_desk_authority,
    evaluator_root,
    verify_desk_authority,
)
from crypto_trade.cup20_desk.live_data import (
    CONTRACT_LIFECYCLE_TRANSITIONS,
    SNAPSHOT_DATASETS,
    SNAPSHOT_FRAMES,
    SNAPSHOT_SCHEMAS,
    AppendInvarianceError,
    AppendResult,
    CacheDriftError,
    LifecycleTransition,
    append_frame,
    cache_manifest,
    fetch_forward,
    verify_cache_manifest,
)
from crypto_trade.cup20_desk.snapshot_forward import (
    MarkCoverageError,
    SeamDiscontinuityError,
    SourceConflictError,
    UniversePolicy,
    UnscoredBoundaryError,
    build_forward_snapshot,
    extend_membership,
    narrow_mark_panel,
    tournament_universe_policy,
)
from crypto_trade.cup20_desk.tick import (
    BRIDGE,
    OFFICIAL,
    PHASES,
    SEAM,
    DeskPinDriftError,
    DeskPins,
    TickResult,
    TickWindowError,
    first_official_boundary,
    persist_tick,
    read_pins,
    run_tick,
)

__all__ = [
    "AUTHORITY_FIELDS",
    "BRIDGE",
    "CONTRACT_LIFECYCLE_TRANSITIONS",
    "OFFICIAL",
    "PHASES",
    "SCHEMA_VERSION",
    "SEAM",
    "SNAPSHOT_DATASETS",
    "SNAPSHOT_FRAMES",
    "SNAPSHOT_SCHEMAS",
    "TOURNAMENT",
    "WINNER_CANDIDATE_ID",
    "WINNER_TEAM_ID",
    "AppendInvarianceError",
    "AppendResult",
    "CacheDriftError",
    "DeploymentChangedError",
    "DeskAuthority",
    "DeskPinDriftError",
    "DeskPins",
    "LifecycleTransition",
    "MarkCoverageError",
    "SeamDiscontinuityError",
    "SourceConflictError",
    "TickResult",
    "TickWindowError",
    "UniversePolicy",
    "UnscoredBoundaryError",
    "append_frame",
    "build_forward_snapshot",
    "cache_manifest",
    "candidate_root",
    "current_desk_authority",
    "evaluator_root",
    "extend_membership",
    "fetch_forward",
    "first_official_boundary",
    "narrow_mark_panel",
    "persist_tick",
    "read_pins",
    "run_tick",
    "tournament_universe_policy",
    "verify_cache_manifest",
    "verify_desk_authority",
]
