#!/usr/bin/env python3
"""Build the frozen weekly Top-12 universe from the audited Top-40 market snapshot.

The source snapshot supplies exchange-authenticated bars, funding, mark prices, and contract
classification.  This builder changes only the point-in-time liquidity membership rule:

* aggregate completed 8h quote volume into UTC days;
* require 180 complete daily observations per symbol;
* at each Monday 00:00 UTC boundary, use only the preceding 180 complete days;
* rank native-crypto USDT perpetuals by median daily quote volume, descending; and
* retain exactly twelve symbols, with the symbol as the deterministic tie-breaker.

All copied and generated bytes are bound into a new manifest.  The source snapshot is never
modified.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import shutil
import stat
import tempfile
from collections.abc import Mapping, Sequence
from pathlib import Path
from typing import Any

import pandas as pd

from crypto_trade.tournament.pure_crypto_universe_v6 import symbol_policy_violations

SOURCE_MANIFEST_RELATIVE = Path("tournament/top40/data_manifest.json")
SOURCE_MANIFEST_SHA256 = "077eb036d262befec80f7013084fe6906859f7c3bbe2f8c193c9d9ec68e367c3"
TARGET_MANIFEST_RELATIVE = Path("tournament/top12/data_manifest.json")
TARGET_SNAPSHOT_RELATIVE = Path("data/top12/snapshot-v1")
TARGET_REPORTS_RELATIVE = Path("reports-top12/common")
BUILD_RECORD_RELATIVE = Path("tournament/top12-v1/universe-build.json")

SOURCE_TO_TARGET = {
    "archive_provenance": TARGET_SNAPSHOT_RELATIVE / "archive_provenance.jsonl",
    "bars": TARGET_SNAPSHOT_RELATIVE / "bars.parquet",
    "contract_metadata": TARGET_SNAPSHOT_RELATIVE / "contract_metadata.parquet",
    "coverage": TARGET_SNAPSHOT_RELATIVE / "coverage.json",
    "exchange_info": TARGET_SNAPSHOT_RELATIVE / "exchange_info.json",
    "funding": TARGET_SNAPSHOT_RELATIVE / "funding.parquet",
    "mark_prices": TARGET_SNAPSHOT_RELATIVE / "mark_prices.parquet",
    "mark_rest_provenance": TARGET_SNAPSHOT_RELATIVE / "mark_rest_provenance.jsonl",
    "membership": TARGET_SNAPSHOT_RELATIVE / "membership.parquet",
    "rest_provenance": TARGET_SNAPSHOT_RELATIVE / "rest_provenance.jsonl",
    "btc_daily_returns": TARGET_REPORTS_RELATIVE / "btc_daily_returns.csv",
    "btc_regimes": TARGET_REPORTS_RELATIVE / "btc_regimes.csv",
}

WINDOW_START = pd.Timestamp("2020-08-03T00:00:00Z")
HARD_END_EXCLUSIVE = pd.Timestamp("2026-07-01T00:00:00Z")
TRAILING_DAYS = 180
UNIVERSE_SIZE = 12
MEMBERSHIP_COLUMNS = (
    "reconstitution_time",
    "symbol",
    "liquidity_rank",
    "trailing_quote_volume",
)


class UniverseBuildError(RuntimeError):
    """The source authority or proposed Top-12 snapshot is invalid."""


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        while chunk := handle.read(1024 * 1024):
            digest.update(chunk)
    return digest.hexdigest()


def _json_bytes(value: object) -> bytes:
    return (json.dumps(value, indent=2, sort_keys=True, ensure_ascii=True) + "\n").encode("utf-8")


def _strict_json(path: Path) -> Mapping[str, Any]:
    def unique(pairs: list[tuple[str, Any]]) -> dict[str, Any]:
        value: dict[str, Any] = {}
        for key, item in pairs:
            if key in value:
                raise UniverseBuildError(f"duplicate JSON key in {path}: {key}")
            value[key] = item
        return value

    try:
        raw = json.loads(path.read_text(encoding="utf-8"), object_pairs_hook=unique)
    except (OSError, UnicodeError, json.JSONDecodeError) as exc:
        raise UniverseBuildError(f"cannot read canonical JSON {path}: {exc}") from exc
    if not isinstance(raw, Mapping):
        raise UniverseBuildError(f"{path} must contain a JSON object")
    return raw


def _regular_file(path: Path, label: str) -> None:
    try:
        info = path.lstat()
    except OSError as exc:
        raise UniverseBuildError(f"{label} is missing: {path}") from exc
    if not stat.S_ISREG(info.st_mode) or path.is_symlink():
        raise UniverseBuildError(f"{label} must be a regular non-symlink file: {path}")


def _source_files(source_root: Path) -> tuple[Mapping[str, Any], dict[str, Mapping[str, Any]]]:
    manifest_path = source_root / SOURCE_MANIFEST_RELATIVE
    _regular_file(manifest_path, "source manifest")
    if _sha256(manifest_path) != SOURCE_MANIFEST_SHA256:
        raise UniverseBuildError("source manifest differs from the audited Top-40 authority")
    manifest = _strict_json(manifest_path)
    raw_files = manifest.get("files")
    if not isinstance(raw_files, list) or len(raw_files) != len(SOURCE_TO_TARGET):
        raise UniverseBuildError("source manifest file inventory is incomplete")
    by_name: dict[str, Mapping[str, Any]] = {}
    for raw in raw_files:
        if not isinstance(raw, Mapping) or set(raw) != {"name", "path", "rows", "sha256", "size"}:
            raise UniverseBuildError("source manifest contains a malformed file entry")
        name = raw.get("name")
        if not isinstance(name, str) or name in by_name:
            raise UniverseBuildError("source manifest file names are invalid or duplicated")
        by_name[name] = raw
    if set(by_name) != set(SOURCE_TO_TARGET):
        raise UniverseBuildError("source manifest names differ from the expected audited snapshot")
    for name, raw in by_name.items():
        relative = raw["path"]
        if (
            not isinstance(relative, str)
            or Path(relative).is_absolute()
            or ".." in Path(relative).parts
        ):
            raise UniverseBuildError(f"unsafe source path for {name}")
        path = source_root / relative
        _regular_file(path, f"source {name}")
        if path.stat().st_size != raw["size"] or _sha256(path) != raw["sha256"]:
            raise UniverseBuildError(f"source bytes changed for {name}")
    return manifest, by_name


def _copy_or_link(source: Path, target: Path) -> None:
    target.parent.mkdir(parents=True, exist_ok=True)
    if target.exists():
        _regular_file(target, "existing target")
        if target.stat().st_size == source.stat().st_size and _sha256(target) == _sha256(source):
            return
        raise UniverseBuildError(f"refusing to overwrite changed target: {target}")
    try:
        os.link(source, target)
    except OSError:
        with tempfile.NamedTemporaryFile(dir=target.parent, delete=False) as handle:
            temporary = Path(handle.name)
        try:
            shutil.copyfile(source, temporary)
            os.replace(temporary, target)
        finally:
            temporary.unlink(missing_ok=True)


def _eligible_metadata(metadata: pd.DataFrame) -> pd.DataFrame:
    expected = {
        "symbol",
        "contract_type",
        "quote_asset",
        "margin_asset",
        "is_crypto",
        "onboard_date",
        "delivery_date",
        "underlying_type",
        "metadata_source",
    }
    if set(metadata.columns) != expected:
        raise UniverseBuildError("contract metadata schema differs from source authority")
    result = metadata.copy()
    result["symbol"] = result["symbol"].astype(str)
    eligible = (
        result["contract_type"].eq("PERPETUAL")
        & result["quote_asset"].eq("USDT")
        & result["margin_asset"].eq("USDT")
        & result["is_crypto"].eq(True)
        & result["symbol"].map(lambda symbol: not symbol_policy_violations(symbol))
    )
    result = result.loc[eligible].copy()
    if result["symbol"].duplicated().any() or result.empty:
        raise UniverseBuildError("eligible contract metadata is empty or duplicated")
    result["onboard_date"] = pd.to_datetime(result["onboard_date"], utc=True, errors="raise")
    result["delivery_date"] = pd.to_datetime(result["delivery_date"], utc=True, errors="raise")
    result = result.set_index("symbol")
    if not result.index.is_unique:
        raise UniverseBuildError("eligible contract metadata index is duplicated")
    return result


def _weekly_membership(bars: pd.DataFrame, metadata: pd.DataFrame) -> pd.DataFrame:
    if set(bars.columns) != {"open_time", "symbol", "quote_volume"}:
        raise UniverseBuildError("bars projection has unexpected columns")
    frame = bars.copy()
    frame["open_time"] = pd.to_datetime(frame["open_time"], utc=True, errors="raise")
    frame["symbol"] = frame["symbol"].astype(str)
    frame["quote_volume"] = pd.to_numeric(frame["quote_volume"], errors="raise")
    if frame["quote_volume"].isna().any() or (frame["quote_volume"] < 0.0).any():
        raise UniverseBuildError("bars contain invalid quote volume")
    frame = frame.loc[frame["symbol"].isin(metadata.index)].copy()
    frame["date"] = frame["open_time"].dt.floor("D")
    daily = (
        frame.groupby(["symbol", "date"], sort=False, observed=True)["quote_volume"]
        .sum()
        .reset_index()
    )

    rows: list[dict[str, object]] = []
    boundaries = pd.date_range(
        WINDOW_START,
        HARD_END_EXCLUSIVE,
        freq="W-MON",
        inclusive="left",
    )
    for boundary in boundaries:
        trailing_start = boundary - pd.Timedelta(days=TRAILING_DAYS)
        window = daily.loc[(daily["date"] >= trailing_start) & (daily["date"] < boundary)]
        statistics = window.groupby("symbol", observed=True).agg(
            trailing_quote_volume=("quote_volume", "median"),
            history_days=("date", "nunique"),
        )
        active = metadata.loc[
            (metadata["onboard_date"] <= trailing_start) & (metadata["delivery_date"] > boundary)
        ].index
        statistics = statistics.loc[
            (statistics["history_days"] == TRAILING_DAYS) & statistics.index.isin(active)
        ]
        statistics = (
            statistics.reset_index()
            .sort_values(
                ["trailing_quote_volume", "symbol"],
                ascending=[False, True],
                kind="mergesort",
            )
            .head(UNIVERSE_SIZE)
        )
        if len(statistics) != UNIVERSE_SIZE:
            raise UniverseBuildError(
                f"boundary {boundary.isoformat()} has only {len(statistics)} eligible symbols"
            )
        for rank, row in enumerate(statistics.itertuples(index=False), start=1):
            rows.append(
                {
                    "reconstitution_time": boundary,
                    "symbol": row.symbol,
                    "liquidity_rank": rank,
                    "trailing_quote_volume": float(row.trailing_quote_volume),
                }
            )

    membership = pd.DataFrame(rows, columns=MEMBERSHIP_COLUMNS)
    if membership.empty or membership.duplicated(["reconstitution_time", "symbol"]).any():
        raise UniverseBuildError("generated membership is empty or duplicated")
    counts = membership.groupby("reconstitution_time", observed=True).size()
    if not counts.eq(UNIVERSE_SIZE).all():
        raise UniverseBuildError("generated membership does not contain twelve symbols every week")
    return membership


def _write_membership(path: Path, membership: pd.DataFrame) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists():
        _regular_file(path, "existing membership")
        observed = pd.read_parquet(path)
        if observed.equals(membership):
            return
        raise UniverseBuildError(f"refusing to overwrite changed membership: {path}")
    with tempfile.NamedTemporaryFile(dir=path.parent, suffix=".parquet", delete=False) as handle:
        temporary = Path(handle.name)
    try:
        membership.to_parquet(
            temporary,
            engine="pyarrow",
            compression="zstd",
            index=False,
        )
        os.replace(temporary, path)
    finally:
        temporary.unlink(missing_ok=True)


def _manifest(
    target_root: Path,
    source_manifest: Mapping[str, Any],
    source_files: Mapping[str, Mapping[str, Any]],
) -> Mapping[str, Any]:
    files: list[dict[str, object]] = []
    for name in SOURCE_TO_TARGET:
        path = target_root / SOURCE_TO_TARGET[name]
        if name == "membership":
            rows = len(pd.read_parquet(path, columns=["symbol"]))
        else:
            rows = int(source_files[name]["rows"])
        files.append(
            {
                "name": name,
                "path": SOURCE_TO_TARGET[name].as_posix(),
                "rows": rows,
                "sha256": _sha256(path),
                "size": path.stat().st_size,
            }
        )
    sources = dict(source_manifest["sources"])
    sources.update(
        {
            "derived_from_manifest": SOURCE_MANIFEST_RELATIVE.as_posix(),
            "derived_from_manifest_sha256": SOURCE_MANIFEST_SHA256,
            "universe_builder_path": "scripts/build_top12_universe.py",
            "universe_rule": (
                "weekly Monday 00:00 UTC top 12 native-crypto USDT perpetuals by median "
                "daily quote volume over 180 complete prior days"
            ),
        }
    )
    limitations = list(source_manifest["limitations"])
    limitations = [
        (
            "Transaction bars before a symbol's first Top-12 admission remain available as "
            "research history but are non-executable; no risk mark is required or synthesized "
            "for those bars."
            if item.startswith("Transaction bars before a symbol's first Top-40 admission")
            else item
        )
        for item in limitations
    ]
    limitations.append(
        "Top-12 membership is a deterministic point-in-time derivation from the bound Top-40 "
        "market-data snapshot; it does not use or preserve the Top-40 membership ranking."
    )
    return {
        "files": files,
        "limitations": limitations,
        "parser_version": "top12-snapshot-v1",
        "schema_version": 1,
        "sources": sources,
        "window": {
            "evaluation_start": WINDOW_START.isoformat(),
            "hard_end_exclusive": HARD_END_EXCLUSIVE.isoformat(),
            "warmup_start": "2020-01-01T00:00:00+00:00",
        },
    }


def _write_exact(path: Path, payload: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists():
        _regular_file(path, "existing authority")
        if path.read_bytes() == payload:
            return
        raise UniverseBuildError(f"refusing to overwrite changed authority: {path}")
    descriptor = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o644)
    try:
        with os.fdopen(descriptor, "wb") as handle:
            handle.write(payload)
            handle.flush()
            os.fsync(handle.fileno())
    except BaseException:
        path.unlink(missing_ok=True)
        raise


def build(root: Path, source_root: Path) -> Mapping[str, Any]:
    root = root.resolve()
    source_root = source_root.resolve()
    source_manifest, source_files = _source_files(source_root)

    for name, target_relative in SOURCE_TO_TARGET.items():
        if name == "membership":
            continue
        source = source_root / str(source_files[name]["path"])
        _copy_or_link(source, root / target_relative)

    bars = pd.read_parquet(
        root / SOURCE_TO_TARGET["bars"],
        columns=["open_time", "symbol", "quote_volume"],
    )
    metadata = pd.read_parquet(root / SOURCE_TO_TARGET["contract_metadata"])
    membership = _weekly_membership(bars, _eligible_metadata(metadata))
    _write_membership(root / SOURCE_TO_TARGET["membership"], membership)

    manifest = _manifest(root, source_manifest, source_files)
    manifest_path = root / TARGET_MANIFEST_RELATIVE
    _write_exact(manifest_path, _json_bytes(manifest))
    build_record = {
        "builder_path": "scripts/build_top12_universe.py",
        "builder_sha256": _sha256(Path(__file__).resolve()),
        "data_manifest_path": TARGET_MANIFEST_RELATIVE.as_posix(),
        "data_manifest_sha256": _sha256(manifest_path),
        "first_reconstitution": membership["reconstitution_time"].min().isoformat(),
        "last_reconstitution": membership["reconstitution_time"].max().isoformat(),
        "membership_rows": len(membership),
        "membership_sha256": _sha256(root / SOURCE_TO_TARGET["membership"]),
        "membership_symbols": membership["symbol"].nunique(),
        "schema_version": 1,
        "source_manifest_sha256": SOURCE_MANIFEST_SHA256,
        "trailing_complete_days": TRAILING_DAYS,
        "universe_size": UNIVERSE_SIZE,
        "weekly_reconstitutions": membership["reconstitution_time"].nunique(),
    }
    _write_exact(root / BUILD_RECORD_RELATIVE, _json_bytes(build_record))
    return build_record


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path.cwd())
    parser.add_argument(
        "--source-root",
        type=Path,
        default=Path.cwd().parent / "quant-portfolio-blind-top40-v4-r1",
    )
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    arguments = _parser().parse_args(argv)
    result = build(arguments.root, arguments.source_root)
    print(json.dumps(result, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
